# TODO create user and access token
# users:
#   - name: renovate
#     fullName: Renovate
#     email: bot@renovateapp.com
#     tokenSecretRef: renovate-secret # ???
organizations:
  - name: ops
    description: Operations
    teams:
      - name: Owners
        members:
          - renovate
repositories:
  - name: homelab2026
    owner: ops
    private: false
    migrate:
      source: https://github.com/candradebh/homelab2026
      mirror: false
  - name: smartdev
    owner: multiversonline
    migrate:
      source: https://github.com/candradebh/smartdev
      mirror: true
  - name: backstage
    owner: multiversonline
    migrate:
      source: https://github.com/candradebh/backstage
      mirror: true
