#  TESTE
#  export KUBECONFIG=$HOME/.kube/homelab2025.yaml
#  kubectl get nodes

- name: Selecionar o nó mestre principal
  set_fact:
    kubeconfig_source_ip: "{{ groups['server'][0] }}"
  when: groups['server'] is defined and groups['server'] | length > 0

- name: Criar diretório ~/.kube se não existir
  file:
    path: "{{ lookup('env','HOME') }}/{{ kubeconfig_local_dir }}"
    state: directory
    mode: "0700"

- name: Copiar kubeconfig do nó mestre para ~/.kube
  fetch:
    src: "{{ kubeconfig_remote_path }}"
    dest: "{{ lookup('env','HOME') }}/{{ kubeconfig_local_dir }}/{{ kubeconfig_local_filename }}"
    flat: true
  delegate_to: "{{ kubeconfig_source_ip }}"
  run_once: true

- name: Substituir 127.0.0.1 pelo IP do nó remoto
  replace:
    path: "{{ lookup('env','HOME') }}/{{ kubeconfig_local_dir }}/{{ kubeconfig_local_filename }}"
    regexp: 'https://127\.0\.0\.1:6443'
    replace: "https://{{ kubeconfig_source_ip }}:6443"

- name: Exportar KUBECONFIG no bashrc
  lineinfile:
    path: "{{ lookup('env','HOME') }}/.bashrc"
    insertafter: EOF
    line: "export KUBECONFIG={{ kubeconfig_local_dir }}/{{ kubeconfig_local_filename }}"
