apiVersion: v2
name: postgres
version: 0.0.0
dependencies:
  - name: app-template
    version: 3.5.1
    repository: https://bjw-s.github.io/helm-charts/
  - name: cloudnative-pg
    version: 0.20.1
    repository: https://cloudnative-pg.github.io/charts
    condition: cnpg.enabled

